# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FyndApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='cast',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='language',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='storyline',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.ImageField(default='no-img.jpg', null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='popularity',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='score',
            field=models.BigIntegerField(null=True),
        ),
    ]
