# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FyndApp', '0003_auto_20180209_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='youtube',
            field=models.URLField(null=True),
        ),
    ]
